package com.nexaiprotocol.protocol.core.network;


/**
 * Represents the output data structure returned by AI model inference requests.
 * This class encapsulates the results generated by the AI model, including
 * predictions, scores, or any other relevant output data.
 *
 * @since 1.0
 */


public class ModelResponse {
}
