package com.nexaiprotocol.model.request;


import lombok.Data;

/**
 * Represents the response generated by an AI model in response to a {@link ChatRequest}.
 * This class encapsulates the output data produced by the model, typically including
 * the generated text or other relevant information.
 *
 * @Data Lombok annotation to automatically generate getters, setters, toString, equals, and hashCode methods
 * @see ChatRequest
 * @since 1.0
 */
@Data
public class ChatResponse {
    private String response;
    private String model;
}
