package com.nexaiprotocol.model.vo;


import lombok.Data;

import java.io.Serial;
import java.io.Serializable;

/**
 * Represents the login credentials provided by a user.
 * This class supports both Web2 (email/password) and Web3 (wallet address/signature) authentication methods.
 *
 * @since 1.0
 */
@Data
public class LoginVo implements Serializable {


    // Web2 Fields
    private String email; // Email address for Web2 login
    private String password; // Password for Web2 login

    // Web3 Fields
    private String walletAddress; // Wallet address for Web3 login (e.g., Ethereum, Solana)
    private String signature; // Signature generated by the wallet for authentication
    private String publicKey; // Public key for cryptographic verification
}
